import Foundation

/// Owns the writable per-user state that must survive replacing the .app bundle.
///
/// The bundle holds only code (binaries, Python venv, the built web app). Anything
/// the user would miss if the bundle were replaced — the SurrealDB store, uploaded
/// source files, and the encryption key protecting stored credentials — lives under
/// Application Support instead.
public enum DataDirectory {
    public static let folderName = "OpenNotebook"

    public enum SetupError: Error, LocalizedError {
        case cannotCreate(URL, underlying: Error)
        case cannotWriteEnv(URL, underlying: Error)

        public var errorDescription: String? {
            switch self {
            case .cannotCreate(let url, let underlying):
                return "Could not create \(url.path): \(underlying.localizedDescription)"
            case .cannotWriteEnv(let url, let underlying):
                return "Could not write \(url.path): \(underlying.localizedDescription)"
            }
        }
    }

    public static func defaultRoot() -> URL {
        FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appending(path: folderName, directoryHint: .isDirectory)
    }

    /// Creates the directory tree and, on first launch only, a fresh `.env`.
    ///
    /// An existing `.env` is never rewritten: it carries the user's
    /// `OPEN_NOTEBOOK_ENCRYPTION_KEY`, and regenerating it would make every stored
    /// credential undecryptable.
    @discardableResult
    public static func prepare(root: URL? = nil) throws -> URL {
        let root = root ?? defaultRoot()
        let fm = FileManager.default

        for sub in ["surreal_data", "data/uploads"] {
            let url = root.appending(path: sub, directoryHint: .isDirectory)
            do {
                try fm.createDirectory(at: url, withIntermediateDirectories: true)
            } catch {
                throw SetupError.cannotCreate(url, underlying: error)
            }
        }

        let envURL = root.appending(path: ".env")
        if !fm.fileExists(atPath: envURL.path) {
            do {
                try generatedEnv().write(to: envURL, atomically: true, encoding: .utf8)
            } catch {
                throw SetupError.cannotWriteEnv(envURL, underlying: error)
            }
        }

        return root
    }

    static func generatedEnv() -> String {
        """
        # Generated by OpenNotebook.app on first launch.
        # OPEN_NOTEBOOK_ENCRYPTION_KEY encrypts stored AI-provider credentials.
        # Do not delete or rotate it — rotating makes existing credentials unreadable.
        OPEN_NOTEBOOK_ENCRYPTION_KEY=\(token(byteCount: 32))

        SURREAL_URL=ws://localhost:8000/rpc
        SURREAL_USER=root
        SURREAL_PASSWORD=\(token(byteCount: 24))
        SURREAL_NAMESPACE=open_notebook
        SURREAL_DATABASE=open_notebook

        OPEN_NOTEBOOK_WORKER_MAX_TASKS=1

        # A corporate HTTP proxy would otherwise tunnel the SurrealDB websocket
        # and the API/worker fail to start with HTTP 403.
        NO_PROXY=localhost,127.0.0.1
        """
    }

    /// Random secret as lowercase hex.
    ///
    /// Deliberately not base64: that alphabet includes `-`, and a password
    /// starting with `-` is parsed by the SurrealDB CLI as a flag rather than as
    /// the value of `--pass`, so the server would refuse to start. Hex cannot
    /// collide with a leading dash.
    static func token(byteCount: Int) -> String {
        var bytes = [UInt8](repeating: 0, count: byteCount)
        var rng = SystemRandomNumberGenerator()
        for index in bytes.indices {
            bytes[index] = UInt8.random(in: .min ... .max, using: &rng)
        }
        return bytes.map { String(format: "%02x", $0) }.joined()
    }
}
